auto generate and update release branch

diff --git a/src/release b/src/release
--- a/src/release
+++ b/src/release
@@ -82,7 +82,7 @@ release(){
     ### verify release
     
     if [ -z "${CURRENT_VERSION}" ]; then
-        echo "ERROR: Could not detect  version!"
+        echo "ERROR: Could not detect version!"
         exit 4
     fi
     
@@ -116,11 +116,17 @@ release(){
         if [ "${RELEASE_BRANCH}" != "${EXPECTED_RELEASE_BRANCH}" ]; then
             echo "WARNING: Expected release Branch[$EXPECTED_RELEASE_BRANCH] but found Branch[$RELEASE_BRANCH]!"
             echo "WARNING: Current Branch[$RELEASE_BRANCH] is not compatible to the pom defined release Version[$RELEASE_VERSION]!"
-            echo "         Should the release branch [$EXPECTED_RELEASE_BRANCH] be auto generated?"
+            echo "         Should the release branch [$EXPECTED_RELEASE_BRANCH] be auto generated and version updated to [${RELEASE_VERSION_MAJOR}.${RELEASE_VERSION_MINOR}.0-SNAPSHOT]?"
             awaitConfirmation &&
             git checkout -b $EXPECTED_RELEASE_BRANCH
             git push origin $EXPECTED_RELEASE_BRANCH
-            RELEASE_BRANCH=$EXPECTED_RELEASE_BRANCH
+            git branch --set-upstream-to=origin/$EXPECTED_RELEASE_BRANCH $EXPECTED_RELEASE_BRANCH
+            mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${RELEASE_VERSION_MAJOR}'.'${RELEASE_VERSION_MINOR}'.0-SNAPSHOT'
+            git commit -am "create release branch ${RELEASE_VERSION_MAJOR}.${RELEASE_VERSION_MINOR}.0-SNAPSHOT"
+            git push
+            echo all done? than restart release
+            release $@           
+            exit 0
         fi
     fi
     
